### ISSUE TITLE
[Feature] Three suggestions

### ISSUE THREAD

**Issue by Matzoh** [Bin-Huang/chatbox#423]
**Problem Description**
1. "I would appreciate it if the command cmd+w could close the window instead of quitting the application."
2. "It would be helpful if the software automatically opens the previous session dialog box on relaunch."
3. "Is it possible to hide the blue update notification dot, especially when the software is already up to date?"
-----------------------

**问题描述**
1. 希望 cmd+w 时改为关闭窗口，而非退出软件。
2. 希望再次打开软件时自动定位到上次的会话框。
3. 能否隐藏掉版本更新的蓝色小点，尤其在版本已经是最新的时候。

**Comment by Bin-Huang** [comment]
Thank you for your feedback! The issue/feature you mentioned has been addressed in the latest application release(official edition). 🎉
Please update to the newest version and give it a try. Let me know if you encounter any further issues or have additional feedback.

感谢你的反馈！你提到的问题/功能已在最新正式版中得到解决 🎉
请更新到最新版本试试看。

**Comment by USMortality** [comment]
Hi, 1. still doesnt work (CMD+W) it closes the app. CMD+H works, but typically on mac W is enough, so I have memorized.... Thx
